[config]
    columns = [
        "First Discovered"
    ]
    in_format =  "%b %d, %Y %H:%M:%S %Z"
    out_format = "%d %b %y"  


# Formatting for date time:
# https://docs.python.org/3/library/datetime.html#strftime-and-strptime-format-codes
